name: Mirror to AuraScale

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to AuraScale repo
        env:
          TOKEN: ${{ secrets.AURASCALE_TOKEN }}
        run: |
          git config --global user.email "reegen@aurascale.co.uk"
          git config --global user.name "aurascale-team"
          git remote add aurascale https://aurascale-team:${TOKEN}@github.com/aurascale-team/thenonsenserealm.git
          git push aurascale HEAD:main --force
